
# Genral
general {
  lock_cmd = hyprlock
  before_sleep_cmd = hyprlock
}

# Idle
# lock after 5 seconds
listener {
  timeout = 300
  on-timeout = hyprlock
}

# turn off display after 10 mins
listener {
  timeout = 600
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# suspend after 30 mins
listener {
  timeout = 1800
  on-timeout = systemctl suspend
}
