source = ~/.cache/wal/colors-hyprland.conf

background {
    monitor =
    path = /home/oreo/walls/wall3.png
    blur_passes = 3
    blur_size = 2
    contrast = 0.95
    brightness = 0.80
    vibrancy = 0.05
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = true
}

label {
    monitor = eDP-1
    text = cmd[update:1000] echo "<span>$(date +"%H:%M:%S")</span>"
    color = $color11
    font_size = 200
    font_family = block
    position = 0, 0
    halign = center
    valign = center
}
